name: package_user
description: A Flutter package providing a customizable list item widget with detailed information.
version: 0.0.8
homepage: https://github.com/RandyRand0m/package_user
repository: https://github.com/RandyRand0m/package_user
issue_tracker: https://github.com/RandyRand0m/package_user/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

