name: package_user
description: A Flutter package providing a customizable list item widget with detailed information.
version: 0.0.9
homepage: https://github.com/RandyRand0m/package_user
repository: https://github.com/RandyRand0m/package_user
issue_tracker: https://github.com/RandyRand0m/package_user/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  barcode: ^2.2.8
  bloc: ^8.1.4
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  intl: ^0.19.0
  table_calendar: ^3.1.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
          weight: 700